### ISSUE TITLE
Fatal Error with v5+

### ISSUE THREAD

**Issue by jkudish** [laravel/scout#294]
I have the `SCOUT_DRIVER` set to `null` when running phpunit tests. Since upgrading to v5 (or 5.0.1, same thing), I get the following error when running my phpunit tests:

```
PHP Fatal error:  Declaration of Laravel\Scout\Engines\NullEngine::map($results, $model) must be compatible with Laravel\Scout\Engines\Engine::map(Laravel\Scout\Builder $builder, $results, $model) in /Users/jkudish/dev/valet/tis/vendor/laravel/scout/src/Engines/NullEngine.php on line 8
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /Users/jkudish/dev/valet/tis/vendor/laravel/framework/src/Illuminate/Container/Container.php:933
Stack trace:
#0 /Users/jkudish/dev/valet/tis/vendor/laravel/framework/src/Illuminate/Container/Container.php(773): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /Users/jkudish/dev/valet/tis/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /Users/jkudish/dev/valet/tis/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
#3 /Users/jkudish/dev/valet/tis/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#4 /Users/jkudish/dev/valet/tis/vendor/laravel/framework/src/Illuminate/Foundation/Bootst in /Users/jkudish/dev/valet/tis/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 933
```

I have since reverted to 4.0.4 and everything is working properly again. 

Looks like [this change](https://github.com/laravel/scout/commit/9f06b9c4d77879d53cf1680740b7f8bf19f78279#diff-c0a1ec7dbf011155e6c41c1f05d39fffR60) is what broke it. I would submit a PR but I am not familiar enough with the inner workings of scout and of that change in particular to say what the correct solution is, other than a revert?

**Comment by jkudish** [comment]
On second thought, I'm thinking the correct fix is to update the `NullEngine` to follow the same interface. Submitted PR in https://github.com/laravel/scout/pull/296

**Comment by jkudish** [comment]
#295 was merged
