### ISSUE TITLE
Array to String conversion with Nova

### ISSUE THREAD

**Issue by m2de** [laravel/scout#316]
In my current implementation I get a random Array to String conversion error when performing a search. The error is thrown here https://github.com/laravel/scout/blob/6.0/src/Engines/AlgoliaEngine.php#L144 with a key of `must` and the value is an empty array.

PHP 7.211
Laravel 5.7.12
Nova 1.1.7

**Comment by driesvints** [comment]
Can you provide a sample request which is being sent to the app? And some relevant code like the model the search is performed on, any controller methods, etc?

**Comment by m2de** [comment]
Hi @driesvints. Thanks for your response. In an effort to do this I managed to determine exactly what was causing it and resolved the issue. I was defining a different model in the `public static $model` to what I was returning in the `public static function newModel()` method (left over from some experimenting). Apologies. Thanks for helping resolve the issue.

**Comment by m2de** [comment]
Ahhhh, correction ... let me start again (I had my filter fix in place) .... I will try and provide some more info shortly ...

**Comment by m2de** [comment]
Model: https://github.com/dewsign/nova-pages/blob/master/src-php/Models/Page.php

Nova Resource: https://github.com/dewsign/nova-pages/blob/master/src-php/Nova/Page.php

There is some code in there from our Elasticsearch implementation (which works fine btw), but we are trying to switch to Algolia which then returned this error.

**Comment by driesvints** [comment]
Can you post the code where the searching happens, the route to it and the request that's being made that causes the error?

**Comment by m2de** [comment]
Thanks @driesvints ... I simply attempt to search within Laravel Nova, it is not code I have written.

![screen recording 2018-11-08 at 11 13 37](https://user-images.githubusercontent.com/17720020/48195545-d6c1ac00-e347-11e8-95ea-06348da77f4e.gif)

Error log:

```
[2018-11-08 11:13:40] local.ERROR: Array to string conversion {"userId":1,"email":"example@email.com","exception":"[object] (ErrorException(code: 0): Array to string conversion at /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/scout/src/Engines/AlgoliaEngine.php:144)
[stacktrace]
#0 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/scout/src/Engines/AlgoliaEngine.php(144): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Array to string...', '/Users/marcomar...', 144, Array)
#1 [internal function]: Laravel\\Scout\\Engines\\AlgoliaEngine->Laravel\\Scout\\Engines\\{closure}(Array, 'must')
#2 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Support/Collection.php(946): array_map(Object(Closure), Array, Array)
#3 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/scout/src/Engines/AlgoliaEngine.php(145): Illuminate\\Support\\Collection->map(Object(Closure))
#4 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/scout/src/Engines/AlgoliaEngine.php(88): Laravel\\Scout\\Engines\\AlgoliaEngine->filters(Object(ScoutElastic\\Builders\\SearchBuilder))
#5 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/scout/src/Engines/Engine.php(77): Laravel\\Scout\\Engines\\AlgoliaEngine->search(Object(ScoutElastic\\Builders\\SearchBuilder))
#6 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/scout/src/Builder.php(181): Laravel\\Scout\\Engines\\Engine->keys(Object(ScoutElastic\\Builders\\SearchBuilder))
#7 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/nova/src/PerformsQueries.php(93): Laravel\\Scout\\Builder->keys()
#8 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/nova/src/PerformsQueries.php(48): Laravel\\Nova\\Resource::initializeQueryUsingScout(Object(Laravel\\Nova\\Http\\Requests\\ResourceIndexRequest), Object(Illuminate\\Database\\Eloquent\\Builder), 'home', NULL)
#9 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/nova/src/PerformsQueries.php(26): Laravel\\Nova\\Resource::initializeQuery(Object(Laravel\\Nova\\Http\\Requests\\ResourceIndexRequest), Object(Illuminate\\Database\\Eloquent\\Builder), 'home', NULL)
#10 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/nova/src/Http/Requests/QueriesResources.php(20): Laravel\\Nova\\Resource::buildIndexQuery(Object(Laravel\\Nova\\Http\\Requests\\ResourceIndexRequest), Object(Illuminate\\Database\\Eloquent\\Builder), 'home', Array, Array, NULL)
#11 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/nova/src/Http/Controllers/ResourceIndexController.php(40): Laravel\\Nova\\Http\\Requests\\ResourceIndexRequest->toQuery()
#12 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/nova/src/Http/Controllers/ResourceIndexController.php(19): Laravel\\Nova\\Http\\Controllers\\ResourceIndexController->paginator(Object(Laravel\\Nova\\Http\\Requests\\ResourceIndexRequest), 'Dewsign\\\\NovaPag...')
#13 [internal function]: Laravel\\Nova\\Http\\Controllers\\ResourceIndexController->handle(Object(Laravel\\Nova\\Http\\Requests\\ResourceIndexRequest), 'pages')
#14 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#15 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('handle', Array)
#16 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Laravel\\Nova\\Http\\Controllers\\ResourceIndexController), 'handle')
#17 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#18 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(679): Illuminate\\Routing\\Route->run()
#19 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/nova/src/Http/Middleware/Authorize.php(18): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Laravel\\Nova\\Http\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/nova/src/Http/Middleware/BootTools.php(20): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Laravel\\Nova\\Http\\Middleware\\BootTools->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/nova/src/Http/Middleware/DispatchServingNovaEvent.php(20): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Laravel\\Nova\\Http\\Middleware\\DispatchServingNovaEvent->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/nova/src/Http/Middleware/Authenticate.php(31): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Laravel\\Nova\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/maxfactor/support/src/Webpage/Middleware/CanonicalHeader.php(18): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Maxfactor\\Support\\Webpage\\Middleware\\CanonicalHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/spatie/laravel-responsecache/src/Middlewares/CacheResponse.php(32): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Spatie\\ResponseCache\\Middlewares\\CacheResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#55 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#56 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#57 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(622): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#58 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(611): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#59 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#60 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#61 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/nova/src/Http/Middleware/ServeNova.php(26): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /Users/marcomark/Packages/dewsign/nova-pages/src-php/Http/Middleware/ServePages.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#65 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Dewsign\\NovaPages\\Http\\Middleware\\ServePages->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#68 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#71 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#74 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#77 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#78 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#79 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#80 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#81 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#82 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#83 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#84 /Users/marcomark/Valet/leightons-maxfactor-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#85 /Users/marcomark/Valet/leightons-maxfactor-laravel/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#86 /Users/marcomark/.composer/vendor/laravel/valet/server.php(147): require('/Users/marcomar...')
#87 {main}
"} 
```

**Comment by driesvints** [comment]
@m2de I really need the request info. Try opening your browser inspector and post the request headers and data that's being sent with the request.

**Comment by m2de** [comment]
Hi @driesvints . No problem, here is the request from the inspector.

## Request Headers

```
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Connection: keep-alive
Cookie: remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d=eyJpdiI6Ik9IUjNVcFhFNDI4anJqS1BNQ3lNU2c9PSIsInZhbHVlIjoiUlZLZmZWaDVIRklSdzFSdDhFMGtBUmtPNTBnUmpZTnJLakNVQ2R1NUc4TExaY0FYU1FzRmYxM2ZlT2pKaTk2MER6Tm44YTZ1eDA4MHZnRWNUdlwvYWpjNGdNUU83MHRcL3pqcjg2bTQyRGwwV08rQTV6T2RFVzZzKzVxbWhRUThhWGJRNkNOdzBJTm1XeFBaY1h3NTlwdTgzY1wvTXJPaUtWeTRYUUV1K0E3OUg0PSIsIm1hYyI6IjM0ODk4ZTk5ODI5OTQ4YTUwMjAwNmRmODM1NjA3NWRhMTAwMzVjY2ZhN2FjZmM5NjgzYjY5MzU1NmVlYzE3NWEifQ%3D%3D; leightons_local_session=eyJpdiI6ImVSNnVzYjdObGJlOUZYRnl4cXpjb3c9PSIsInZhbHVlIjoieFwvUmNhR1pBQUg0dDdXRytKeTVGY2JHMCt3SEVOYXdiZ3luT1plNVFpSjVXZ1hCMENpQit5YVBuNFVsblJmRGEiLCJtYWMiOiJkZjYxZTcyZGMzNDIzY2Y3N2Q4YzBjNTNkN2ZkYjNmM2I0MWM2NzE4MzU0NDk2MDYwNzc3NjI1M2Q4YzEwYTAyIn0%3D
Host: leightons-maxfactor-laravel.test
Referer: http://leightons-maxfactor-laravel.test/admin/resources/pages?pages_page=1&pages_search=homep&pages_filter=W3siY2xhc3MiOiJEZXdzaWduXFxOb3ZhUGFnZXNcXE5vdmFcXEZpbHRlcnNcXEFjdGl2ZVN0YXRlIiwidmFsdWUiOnRydWV9LHsiY2xhc3MiOiJEZXdzaWduXFxOb3ZhUGFnZXNcXE5vdmFcXEZpbHRlcnNcXFBhZ2VUeXBlIiwidmFsdWUiOiJwYXJlbnQifV0%3D
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
X-CSRF-TOKEN: 0sjrAqmPQ7gWXJPuYxtbf8CArsXB3zpXh85MAsSG
X-Requested-With: XMLHttpRequest
```

## Query String Parameters

```
search: homep
filters: W3siY2xhc3MiOiJEZXdzaWduXFxOb3ZhUGFnZXNcXE5vdmFcXEZpbHRlcnNcXEFjdGl2ZVN0YXRlIiwidmFsdWUiOnRydWV9LHsiY2xhc3MiOiJEZXdzaWduXFxOb3ZhUGFnZXNcXE5vdmFcXEZpbHRlcnNcXFBhZ2VUeXBlIiwidmFsdWUiOiJwYXJlbnQifV0=
orderBy: 
orderByDirection: desc
perPage: 25
trashed: 
page: 1
viaResource: 
viaResourceId: 
viaRelationship: 
relationshipType: 
```

Hope that helps. Please let me know if you need anything else.

**Comment by driesvints** [comment]
I honestly have no clue why the search value is being sent as an array. Might be something Scout specific. 

As for your PR: I don't think filtering out the array is a good idea because you're just hiding the actual error. I think it's best that the array to string conversion is always thrown as it's a good indication that there's something going wrong in the place where the search is being passed to Scout.

I think it might be best to open an issue on the nova-issues repo to find out why the result is being passed as an array: https://github.com/laravel/nova-issues/issues

Hope you can figure it out. Sorry that this isn't much of help.

**Comment by m2de** [comment]
Fair enough, will do some more debugging. My thinking was that removing array values fixed the issue without affecting the results, but totally understand.

Thanks for looking into it.

**Comment by gerasart** [comment]
use HasTranslations;
