### ISSUE TITLE
php artisan scout:import error

### ISSUE THREAD

**Issue by aoeng** [laravel/scout#779]
laravel 10.31
scout 10.5
laravel-scout-elasticsearch 7.4.0
laravel-admin 1.8.19

```
//php artisan scout:import 
[2023-11-10 16:02:19] local.ERROR: Cannot use Encore\Admin\Form as Form because the name is already in use on line 21 {"exception":"[object] (PhpParser\\Error(code: 0): Cannot use Encore\\Admin\\Form as Form because the name is already in use on line 21 at /www/wwwroot/Ticket/vendor/nikic/php-parser/lib/PhpParser/NameContext.php:71)
[stacktrace]
#0 /www/wwwroot/Ticket/vendor/nikic/php-parser/lib/PhpParser/NodeVisitor/NameResolver.php(171): PhpParser\\NameContext->addAlias()
#1 /www/wwwroot/Ticket/vendor/nikic/php-parser/lib/PhpParser/NodeVisitor/NameResolver.php(63): PhpParser\\NodeVisitor\\NameResolver->addAlias()
#2 /www/wwwroot/Ticket/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): PhpParser\\NodeVisitor\\NameResolver->enterNode()
#3 /www/wwwroot/Ticket/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\\NodeTraverser->traverseArray()
#4 /www/wwwroot/Ticket/vendor/matchish/laravel-scout-elasticsearch/src/Searchable/SearchableListFactory.php(134): PhpParser\\NodeTraverser->traverse()
#5 /www/wwwroot/Ticket/vendor/matchish/laravel-scout-elasticsearch/src/Searchable/SearchableListFactory.php(105): Matchish\\ScoutElasticSearch\\Searchable\\SearchableListFactory->getStmts()
#6 /www/wwwroot/Ticket/vendor/matchish/laravel-scout-elasticsearch/src/Searchable/SearchableListFactory.php(91): Matchish\\ScoutElasticSearch\\Searchable\\SearchableListFactory->getProjectClasses()
#7 /www/wwwroot/Ticket/vendor/matchish/laravel-scout-elasticsearch/src/Searchable/SearchableListFactory.php(80): Matchish\\ScoutElasticSearch\\Searchable\\SearchableListFactory->getSearchableClasses()
#8 /www/wwwroot/Ticket/vendor/matchish/laravel-scout-elasticsearch/src/Searchable/SearchableListFactory.php(68): Matchish\\ScoutElasticSearch\\Searchable\\SearchableListFactory->find()
#9 /www/wwwroot/Ticket/vendor/matchish/laravel-scout-elasticsearch/src/Console/Commands/ImportCommand.php(43): Matchish\\ScoutElasticSearch\\Searchable\\SearchableListFactory->make()
#10 /www/wwwroot/Ticket/vendor/laravel/framework/src/Illuminate/Conditionable/Traits/Conditionable.php(34): Matchish\\ScoutElasticSearch\\Console\\Commands\\ImportCommand->Matchish\\ScoutElasticSearch\\Console\\Commands\\{closure}()
#11 /www/wwwroot/Ticket/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(531): Illuminate\\Support\\Collection->when()
#12 /www/wwwroot/Ticket/vendor/matchish/laravel-scout-elasticsearch/src/Console/Commands/ImportCommand.php(44): Illuminate\\Support\\Collection->whenEmpty()
#13 /www/wwwroot/Ticket/vendor/matchish/laravel-scout-elasticsearch/src/Console/Commands/ImportCommand.php(32): Matchish\\ScoutElasticSearch\\Console\\Commands\\ImportCommand->searchableList()
#14 /www/wwwroot/Ticket/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Matchish\\ScoutElasticSearch\\Console\\Commands\\ImportCommand->handle()
#15 /www/wwwroot/Ticket/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /www/wwwroot/Ticket/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#17 /www/wwwroot/Ticket/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#18 /www/wwwroot/Ticket/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#19 /www/wwwroot/Ticket/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#20 /www/wwwroot/Ticket/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#21 /www/wwwroot/Ticket/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\\Component\\Console\\Command\\Command->run()
#22 /www/wwwroot/Ticket/vendor/symfony/console/Application.php(1081): Illuminate\\Console\\Command->run()
#23 /www/wwwroot/Ticket/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()
#24 /www/wwwroot/Ticket/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()
#25 /www/wwwroot/Ticket/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#26 /www/wwwroot/Ticket/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#27 {main}
"} 
```
ubuntu service  error ,but success in win11,
I need help!

**Comment by mmachatschek** [comment]
Based on looking at the stack trace, I don't see any issue with laravel/scout here. you should seek for assistance on the laravel-scout-elasticsearch repo instead

**Comment by aoeng** [comment]
I change driver to anouther "algolia",but still so.The configuration file doesn't seem to be working

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
